In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Flatten

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("just loved it!",30)

[5, 8, 28]

In [4]:
voc_size=30
encode=[one_hot(i,voc_size) for i in reviews]

In [5]:
encode

[[17, 17],
 [5, 12],
 [17, 23],
 [5, 8, 28],
 [18, 17, 10],
 [26, 17],
 [5, 17, 12],
 [27, 11],
 [27, 3],
 [17, 17]]

In [6]:
max_lenght=4
paddu=pad_sequences(encode,maxlen=max_lenght,padding='post')
print(paddu)
len(paddu)

[[17 17  0  0]
 [ 5 12  0  0]
 [17 23  0  0]
 [ 5  8 28  0]
 [18 17 10  0]
 [26 17  0  0]
 [ 5 17 12  0]
 [27 11  0  0]
 [27  3  0  0]
 [17 17  0  0]]


10

In [7]:
vector_size=4
model=Sequential()
model.add(Embedding(voc_size,vector_size,input_length=max_lenght,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [8]:
X=paddu
y=sentiment
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X,sentiment,epochs=10)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 0.6881 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 0.6870 - accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6859 - accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 0.6848 - accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 3ms/step - loss: 0.6836 - accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6825 - accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6814 - accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6803 - accuracy: 0.6000
Epoch 9/10
1/1 [==============================] - 0s 3ms/step - loss: 0.6792 - accuracy: 0.7000
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 0.6780 - accuracy: 0.7000


In [9]:
model.evaluate(X,y)

1/1 [==============================] - 0s 128ms/step - loss: 0.6769 - accuracy: 0.7000


[0.676923394203186, 0.699999988079071]

In [10]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [11]:
weights[13]

array([-0.03697597, -0.04776433, -0.01168537,  0.00041944], dtype=float32)

In [2]:
!pip install gensim
!pip install python-Levenshtein

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0.12.2-cp39-cp39-win_amd64.whl size=83823 sha256=1d2a57918b16f22aa4d762cc076980ee736e3a77eb01d3bb9973fb4571a557c5
  Stored in directory: c:\users\somashekhar\appdata\local\pip\cache\wheels\46\4a\6c\164a1d9dd67c82d208f19d869ad0a517a0c5a6117f608c53e6
Successfully built python-Levenshtein


In [4]:
import gensim
import pandas as pd

In [6]:
df=pd.read_json('G:\TENSOR\Cell_Phones_and_Accessories_5.json',lines=True)

In [7]:
df

reviewerID        asin       reviewerName helpful  \
0       A30TL5EWN6DFXT  120401325X          christina  [0, 0]   
1        ASY55RVNIL0UD  120401325X           emily l.  [0, 0]   
2       A2TMXE2AFO7ONB  120401325X              Erica  [0, 0]   
3        AWJ0WZQYMYFQ4  120401325X                 JM  [4, 4]   
4        ATX7CZYFXI1KW  120401325X   patrice m rogoza  [2, 3]   
...                ...         ...                ...     ...   
194434  A1YMNTFLNDYQ1F  B00LORXVUE    eyeused2loveher  [0, 0]   
194435  A15TX8B2L8B20S  B00LORXVUE       Jon Davidson  [0, 0]   
194436  A3JI7QRZO1QG8X  B00LORXVUE  Joyce M. Davidson  [0, 0]   
194437  A1NHB2VC68YQNM  B00LORXVUE     Nurse Farrugia  [0, 0]   
194438  A1AG6U022WHXBF  B00LORXVUE     Trisha Crocker  [0, 0]   

                                               reviewText  overall  \
0       They look good and stick good! I just don't li...        4   
1       These stickers work like the review says they ...        5   
2       These are awesome and make my phone look so st...        5   
3       Item arrived in great time and was in perfect ...        4   
4       awesome! stays on, and looks great. can be use...        5   
...                                                   ...      ...   
194434  Works great just like my original one. I reall...        5   
194435  Great product. Great packaging. High quality a...        5   
194436  This is a great cable, just as good as the mor...        5   
194437  I really like it becasue it works well with my...        5   
194438  product as described, I have wasted a lot of m...        5   

                                                  summary  unixReviewTime  \
0                                              Looks Good      1400630400   
1                                   Really great product.      1389657600   
2                                          LOVE LOVE LOVE      1403740800   
3                                                   Cute!      1382313600   
4               leopard home button sticker for iphone 4s      1359849600   
...                                                   ...             ...   
194434                           This works just perfect!      1405900800   
194435           Great replacement cable. Apple certified      1405900800   
194436                                       Real quality      1405900800   
194437  I really like it becasue it works well with my...      1405814400   
194438              I have wasted a lot of money on cords      1405900800   

         reviewTime  
0       05 21, 2014  
1       01 14, 2014  
2       06 26, 2014  
3       10 21, 2013  
4        02 3, 2013  
...             ...  
194434  07 21, 2014  
194435  07 21, 2014  
194436  07 21, 2014  
194437  07 20, 2014  
194438  07 21, 2014  

[194439 rows x 9 columns]

In [8]:
df.shape

(194439, 9)

In [9]:
review_text=df.reviewText.apply(gensim.utils.simple_preprocess)

In [10]:
review_text

0         [they, look, good, and, stick, good, just, don...
1         [these, stickers, work, like, the, review, say...
2         [these, are, awesome, and, make, my, phone, lo...
3         [item, arrived, in, great, time, and, was, in,...
4         [awesome, stays, on, and, looks, great, can, b...
                                ...                        
194434    [works, great, just, like, my, original, one, ...
194435    [great, product, great, packaging, high, quali...
194436    [this, is, great, cable, just, as, good, as, t...
194437    [really, like, it, becasue, it, works, well, w...
194438    [product, as, described, have, wasted, lot, of...
Name: reviewText, Length: 194439, dtype: object

In [14]:
review_text.loc[0]

['they',
 'look',
 'good',
 'and',
 'stick',
 'good',
 'just',
 'don',
 'like',
 'the',
 'rounded',
 'shape',
 'because',
 'was',
 'always',
 'bumping',
 'it',
 'and',
 'siri',
 'kept',
 'popping',
 'up',
 'and',
 'it',
 'was',
 'irritating',
 'just',
 'won',
 'buy',
 'product',
 'like',
 'this',
 'again']

In [13]:
df.reviewText.loc[0]

"They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again"

In [16]:
model=gensim.models.Word2Vec(
window=10,
min_count=2,
workers=4,
)

In [18]:
model.build_vocab(review_text,progress_per=1000)

In [19]:
model.train(review_text,total_examples=model.corpus_count,epochs=model.epochs)

(61506520, 83868975)

In [20]:
model.save("./word2vec-amazon-cell-accessories-reviews-short.model")

In [21]:
model.wv.similarity(w1="cheap", w2="inexpensive")

[('terrible', 0.6869036555290222),
 ('shabby', 0.6128516793251038),
 ('horrible', 0.6100680232048035),
 ('good', 0.5893303751945496),
 ('awful', 0.5429758429527283),
 ('okay', 0.5293138027191162),
 ('poor', 0.5245975255966187),
 ('pathetic', 0.5102907419204712),
 ('legit', 0.5079593658447266),
 ('cheap', 0.5060308575630188)]

In [23]:
model.wv.similarity(w1="won", w2="was")

-0.11370071

In [24]:
model.wv.similarity(w1="terrible", w2="horrible")

0.89949065

In [ ]:
model.wv.similarity(w1="", w2="horrible")